commands = {'bye': 'Bye! It was nice having you here, do come back soon! :=)',
 'bye!': 'Bye! It was nice having you here, do come back soon! :=) ',
 'code': 'My code is at https://github.com/sunu/logbot. Feel free to fork me.',
 'hello': "Hi! How're you doing?",
 'hello!': "Hi! How're you doing?",
 'hi': 'Hello wonderful person!',
 'hi!': 'Hello wonderful person!',
 'how are you?': "I'm doing fine. What about you?",
 'logs': 'IRC chat logs can be found at http://irclogs.wfs-india.org',
 'thank you': "You're Welcome!",
 'website': 'Please visit us at http://www.wfs-india.org',
 'who are you': 'Hi, I am Floggy, junior assistant of Darth Vader from the planet Vulcan, and a bot on the #wfs-india channel on freenode.',
 'who are you?': 'Hi, I am Floggy, junior assistant of Darth Vader from the planet Vulcan, and a bot on the #wfs-india channel on freenode.'}